from aiogram.utils.keyboard import InlineKeyboardBuilder

from app.i18n import t

KEYS = [
    "btn_menu",
    "btn_profile",
    "btn_deal",
    "btn_faq",
    "btn_support",
    "btn_inventory",
    "btn_history",
    "btn_about",
    "btn_admin",
    "btn_feed",
    "active_deal_btn",
    "btn_req",
    "deposit",
    "withdraw",
    "change_lang",
    "lang_ru",
    "lang_en",
    "req_card",
    "req_phone",
    "req_ton",
    "deal_cur_ton",
    "deal_cur_usdt",
    "deposit_asset_ton",
    "deposit_asset_usdt",
    "btn_back",
    "btn_cancel",
    "btn_yes",
    "btn_no",
    "deposit_check",
    "deal_buyer",
    "deal_seller",
    "deal_kind_goods",
    "deal_kind_ton",
    "deal_private",
    "deal_public",
    "deal_take",
    "deal_manual_btn",
    "deal_send",
    "deal_reviews",
    "deal_accept",
    "deal_decline",
    "deal_set_price",
    "deal_set_nft",
    "deal_set_desc",
    "deal_set_ton",
    "deal_set_rub",
    "deal_set_buy_ton",
    "deal_check_ton",
    "deal_rub_paid",
    "deal_rub_ok",
    "deal_pay",
    "deal_pdf",
    "deal_confirm",
    "deal_dispute",
    "deal_dispute_thread",
    "deal_dispute_evidence",
    "deal_chat",
    "deal_photo",
    "deal_dispute_done",
    "deal_cancel",
    "deal_agree",
    "deal_refuse",
    "deal_review_skip",
    "admin_stats",
    "admin_disputes",
    "admin_deposits",
    "admin_withdraws",
    "admin_ban",
    "admin_unban",
    "admin_bans",
    "admin_faq",
    "admin_screens",
    "admin_balance",
    "admin_mail",
    "admin_settings",
    "admin_wallets",
    "admin_sessions",
    "admin_admins",
    "admin_adm_add",
    "admin_buttons",
    "admin_buyer",
    "admin_seller",
    "admin_write_seller",
    "admin_write_buyer",
    "admin_confirm",
    "admin_reject",
    "admin_faq_add",
    "admin_faq_del",
    "admin_faq_photo",
    "admin_reply",
    "sub_open",
    "sub_check",
]

DEFAULT_STYLE = {
    "btn_deal": "success",
    "btn_profile": "primary",
    "btn_support": "success",
    "btn_faq": "primary",
    "btn_menu": "primary",
    "btn_inventory": "primary",
    "btn_history": "primary",
    "btn_about": "primary",
    "btn_admin": "danger",
    "btn_req": "primary",
    "btn_back": "primary",
    "deposit": "success",
    "withdraw": "primary",
    "change_lang": "primary",
    "lang_ru": "primary",
    "lang_en": "primary",
    "req_card": "primary",
    "req_phone": "primary",
    "req_ton": "primary",
    "deal_cur_ton": "primary",
    "deal_cur_usdt": "success",
    "deposit_asset_ton": "primary",
    "deposit_asset_usdt": "success",
    "deposit_check": "success",
    "deal_send": "success",
    "deal_accept": "success",
    "deal_decline": "danger",
    "deal_pay": "success",
    "deal_pdf": "success",
    "deal_confirm": "success",
    "deal_kind_goods": "primary",
    "deal_kind_ton": "primary",
    "deal_buyer": "primary",
    "deal_seller": "primary",
    "deal_private": "primary",
    "deal_public": "success",
    "deal_take": "success",
    "deal_manual_btn": "primary",
    "deal_reviews": "primary",
    "btn_feed": "primary",
    "active_deal_btn": "success",
    "deal_set_price": "primary",
    "deal_set_nft": "primary",
    "deal_set_desc": "primary",
    "deal_set_ton": "primary",
    "deal_set_rub": "primary",
    "deal_set_buy_ton": "primary",
    "deal_check_ton": "success",
    "deal_rub_paid": "success",
    "deal_rub_ok": "success",
    "deal_dispute": "danger",
    "deal_dispute_thread": "primary",
    "deal_dispute_evidence": "primary",
    "deal_chat": "primary",
    "deal_photo": "primary",
    "deal_dispute_done": "success",
    "deal_review_skip": "primary",
    "admin_faq_add": "success",
    "admin_faq_del": "danger",
    "admin_faq_photo": "primary",
    "admin_reply": "primary",
    "admin_write_seller": "primary",
    "admin_write_buyer": "primary",
    "admin_bans": "danger",
    "admin_ban": "danger",
    "admin_unban": "success",
    "admin_stats": "primary",
    "admin_disputes": "danger",
    "admin_deposits": "success",
    "admin_withdraws": "primary",
    "admin_faq": "primary",
    "admin_screens": "primary",
    "admin_balance": "primary",
    "admin_mail": "primary",
    "admin_settings": "primary",
    "admin_wallets": "success",
    "admin_sessions": "primary",
    "admin_admins": "danger",
    "admin_adm_add": "success",
    "deal_cancel": "danger",
    "btn_yes": "success",
    "btn_no": "danger",
    "deal_agree": "success",
    "deal_refuse": "danger",
    "btn_cancel": "danger",
    "admin_confirm": "success",
    "admin_reject": "danger",
    "admin_buyer": "success",
    "admin_seller": "primary",
    "admin_buttons": "primary",
    "sub_open": "success",
    "sub_check": "success",
}

EMOJI = {
    "btn_menu": "🏠",
    "btn_profile": "👤",
    "btn_deal": "🛡️",
    "btn_faq": "❓",
    "btn_support": "💬",
    "btn_inventory": "🎁",
    "btn_history": "📜",
    "btn_about": "ℹ️",
    "btn_admin": "🎛",
    "btn_feed": "🛒",
    "active_deal_btn": "⚡",
    "btn_req": "💳",
    "deposit": "⬇️",
    "withdraw": "⬆️",
    "change_lang": "🌐",
    "lang_ru": "🇷🇺",
    "lang_en": "🇬🇧",
    "req_card": "💳",
    "req_phone": "📱",
    "req_ton": "💎",
    "deal_cur_ton": "💎",
    "deal_cur_usdt": "💵",
    "deposit_asset_ton": "💎",
    "deposit_asset_usdt": "💵",
    "btn_back": "⬅️",
    "btn_cancel": "❌",
    "btn_yes": "✅",
    "btn_no": "❌",
    "deposit_check": "🔍",
    "deal_buyer": "🛒",
    "deal_seller": "💼",
    "deal_kind_goods": "📦",
    "deal_kind_ton": "💎",
    "deal_private": "👤",
    "deal_public": "📣",
    "deal_take": "✅",
    "deal_manual_btn": "📋",
    "deal_send": "📤",
    "deal_reviews": "⭐",
    "deal_accept": "✅",
    "deal_decline": "❌",
    "deal_set_price": "💰",
    "deal_set_nft": "🎁",
    "deal_set_desc": "📝",
    "deal_set_ton": "💎",
    "deal_set_rub": "₽",
    "deal_set_buy_ton": "📥",
    "deal_check_ton": "🔍",
    "deal_rub_paid": "💸",
    "deal_rub_ok": "✅",
    "deal_pay": "💳",
    "deal_pdf": "📄",
    "deal_confirm": "✅",
    "deal_dispute": "⚠️",
    "deal_dispute_thread": "💬",
    "deal_dispute_evidence": "📎",
    "deal_chat": "💬",
    "deal_photo": "📷",
    "deal_dispute_done": "✅",
    "deal_cancel": "🗑",
    "deal_agree": "✅",
    "deal_refuse": "❌",
    "deal_review_skip": "➡️",
    "admin_stats": "📊",
    "admin_disputes": "⚖️",
    "admin_deposits": "⬇️",
    "admin_withdraws": "⬆️",
    "admin_ban": "🚫",
    "admin_unban": "✅",
    "admin_bans": "🚷",
    "admin_faq": "❓",
    "admin_screens": "🖼",
    "admin_balance": "💰",
    "admin_mail": "📣",
    "admin_settings": "⚙️",
    "admin_wallets": "💎",
    "admin_sessions": "🔐",
    "admin_admins": "👑",
    "admin_adm_add": "➕",
    "admin_buttons": "🎛",
    "admin_buyer": "🛒",
    "admin_seller": "💼",
    "admin_confirm": "✅",
    "admin_reject": "❌",
    "admin_faq_add": "➕",
    "admin_faq_del": "🗑",
    "admin_faq_photo": "🖼",
    "admin_reply": "✉️",
    "admin_write_seller": "💼",
    "admin_write_buyer": "🛒",
    "sub_open": "📢",
    "sub_check": "✅",
}

STYLES = ("primary", "success", "danger")
PAGE_SIZE = 7


class Theme:
    def __init__(self, rows: dict[str, dict]) -> None:
        self.rows = rows

    def text(self, key: str, lang: str, **fmt) -> str:
        row = self.rows.get(key) or {}
        custom = row.get(f"label_{lang}") or row.get("label_ru") or row.get("label_en")
        raw = custom or t(lang, key)
        if fmt:
            try:
                raw = raw.format(**fmt)
            except (KeyError, IndexError, ValueError):
                pass
        icon = EMOJI.get(key)
        if self.emoji(key):
            if icon and raw.startswith(icon):
                return raw[len(icon) :].lstrip()
            return raw
        if icon and icon not in raw:
            return f"{icon} {raw}"
        return raw

    def style(self, key: str) -> str | None:
        row = self.rows.get(key)
        if row is not None and row.get("style") is not None:
            return row["style"] or None
        return DEFAULT_STYLE.get(key)

    def emoji(self, key: str) -> str | None:
        row = self.rows.get(key) or {}
        value = (row.get("emoji_id") or "").strip()
        return value or None

    def add(self, kb: InlineKeyboardBuilder, key: str, lang: str, **kwargs) -> None:
        fmt = kwargs.pop("fmt", None) or {}
        kb.button(
            text=self.text(key, lang, **fmt),
            style=self.style(key),
            icon_custom_emoji_id=self.emoji(key),
            **kwargs,
        )
